name: Test-portfolio

on:
  push:
    branches:
    - main
jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials and Deploy to S3 bucket
        uses: aws-actions/configure-aws-credentials@v4
        with:
           command: cp
           source: ./protfolio/
           destination: s3://my-test-portfolio-bucket/protfolio/
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-2
           
